name: MiMMO
markdown: redcarpet
highlighter: rouge
baseurl: /MIMMO

exclude: [_manual]

collections:
  overview:
    output: true

sections:
    overview:
        name: Overview

        subsections:
            basics:
                name: Basics
                url: basics.html
            morphing:
                name: Morphing
                url: morphing.html
            wrappers:
                name: Wrappers
                url: wrappers.html
            tools:
                name: Tools
                url: tools.html

    examples:
        name: Examples
        url:

    documentation:
        name: Documentation

        subsections:
            installation:
                name: Installation guide
                url: installation.html
            manual:
                name: Programmer's manual
                url: manual/1.0.0/index.xhtml

    downloads:
        name: Downloads
        url:

gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed